// <auto-generated />
using apm.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace apm.Migrations
{
    [DbContext(typeof(ApmContext))]
    partial class ApmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("apm.Models.Point", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<float>("lat");

                    b.Property<float>("lng");

                    b.Property<int>("pm01_0");

                    b.Property<int>("pm02_5");

                    b.Property<int>("pm10_0");

                    b.HasKey("id");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("apm.Models.Station", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("additionDate");

                    b.Property<bool>("isMobile");

                    b.Property<string>("sensor");

                    b.HasKey("id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("apm.Models.Statistic", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("pm01_0");

                    b.Property<int>("pm02_5");

                    b.Property<int>("pm10_0");

                    b.HasKey("id");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("apm.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<string>("phoneNumber");

                    b.Property<string>("surname");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
